USE BATTERIES;

INSERT INTO BATTERIES VALUES (0, 'BATERIA_UNO', 6, 7);
INSERT INTO BATTERIES VALUES (0, 'BATERIA_DOS', 8, 9);
INSERT INTO BATTERIES VALUES (0, 'BATERIA_TRES', 10, 11);
COMMIT;

INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 5, ADDDATE(NOW(), INTERVAL 0 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 7, ADDDATE(NOW(), INTERVAL 5 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 4, ADDDATE(NOW(), INTERVAL 10 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 2, ADDDATE(NOW(), INTERVAL 15 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 7, ADDDATE(NOW(), INTERVAL 20 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 8, ADDDATE(NOW(), INTERVAL 25 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 9, ADDDATE(NOW(), INTERVAL 30 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 1, 4, ADDDATE(NOW(), INTERVAL 35 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 2, 8, ADDDATE(NOW(), INTERVAL 0 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 2, 9, ADDDATE(NOW(), INTERVAL 5 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 2, 4, ADDDATE(NOW(), INTERVAL 10 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 3, 9, ADDDATE(NOW(), INTERVAL 0 SECOND));
INSERT INTO BATTERIES_ENTRY VALUES (0, 3, 4, ADDDATE(NOW(), INTERVAL 5 SECOND));
COMMIT;