
/*CREATE DATABASE BATTERIES;

CREATE USER 'Batteries'@'localhost' IDENTIFIED BY 'Batteries';
GRANT ALL PRIVILEGES ON BATTERIES.* TO 'Batteries'@'localhost';
*/
USE BATTERIES;

DROP TABLE IF EXISTS BATTERIES_ENTRY;
DROP TABLE IF EXISTS BATTERIES;

CREATE TABLE BATTERIES(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    INPUTPIN INT(255),
    OUTPUTPIN INT(255),
    CONSTRAINT PK_BATTERIES PRIMARY KEY(ID),
    CONSTRAINT UQ_BATTERIES UNIQUE(NOMBRE)
) ENGINE=InnoDb;

CREATE TABLE BATTERIES_ENTRY(
    ID INT(255) AUTO_INCREMENT NOT NULL,
    BATTERIES_ID INT(255) NOT NULL,
    VOLTAGE INT(255) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_BATTERIES_ENTRY PRIMARY KEY(ID, BATTERIES_ID)
) ENGINE=InnoDb;